name: vsartist
description: Artist application for vibespot music player.

version: 2.0.0+30

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # assets_audio_player: ^3.0.3+6  
  animations: ^2.0.1
  built_collection: ^5.1.0
  built_value: ^8.1.1
  cupertino_icons: ^1.0.2 
  dospace: 
   git:
      url: https://github.com/wiseminds/dospace.git
      ref: 252094ba8ab6e11fb292994a996f39125d66238a 
  equatable: ^2.0.3
  google_place: ^0.4.3
  # google_places_for_flutter: ^1.0.1
  # sqflite: ^2.0.0+4
  path_provider: ^2.0.2
  rxdart: ^0.27.1
  connectivity: ^3.0.6
  extended_image: ^4.1.0
  flutter_blurhash: ^0.6.0
  shared_preferences: ^2.0.7
  image_picker: ^0.8.3+3
  # bloc: ^0.14.1
  flutter_bloc: ^7.2.0
  file_picker: ^4.0.3
  image_cropper: ^1.4.1
  flutter_secure_storage: ^4.2.0
  flutter_svg: ^0.22.0
  dio: ^4.0.0
  # flutter_paystack: ^1.0.5+1
  flutter_paystack:
    git:
      url: https://github.com/definitelyme/flutter_paystack.git
      ref: a4a33c3dd0a12f46d655a2e63d11e9f20ba82d01
  flutter_screenutil: ^5.0.0+2
  just_audio: ^0.9.11
  jwt_decoder: ^2.0.1
  url_launcher: ^6.0.9 
  # email_validator: ^2.0.1
  # toast: ^0.1.4
  fluttertoast: ^8.0.8
  get_it: ^7.2.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  launch_review: ^3.0.1
  shimmer: ^2.0.0
  store_redirect: ^2.0.0
  simple_logger: ^1.8.1
  # share_plus: ^3.0.4
  # multiselect_formfield: ^0.1.6
  pull_to_refresh: ^2.0.0
  # music: ^1.0.3
  uuid: ^3.0.1
  firebase_messaging:
  firebase_core:
  get:
  http:

dependency_overrides:
  firebase_messaging_platform_interface: 3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  built_value_generator: ^8.0.3   


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   - assets/images/ 
   - assets/svg/ 
   - assets/images/onboard/ 

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          style: italic

  
